module "ec2"{
    source = "path to vpc module"
    id_of_vpc = "....."
    public_security_group_name = "public-security-group"
    private_security_group_name = "private-security-group"
    ec2_sg_owner = "data-platform-team"
    ec2_sg_environment = "dev"
    public_sg_inbound_traffic = "0.0.0.0/0"
    public_sg_outbound_traffic = "0.0.0.0/0"
    private_sg_inbound_traffic = "#REFERENCE CIDR BLOCK RANGE OF PUBLIC SUBNET"
    private_sg_outbound_traffic = "0.0.0.0/0"
    sg_ip_protocol = "-1"
    port_number = "22"
    public_ssh_keyname = "....."
    public_ssh_filepath = "....."
    public_ec2_ami = "ami-08ec94f928cf25a9d"
    private_ec2_ami = "ami-08ec94f928cf25a9d"
    public_ec2_instance_type = "t2.micro"
    private_ec2_instance_type = "t2.micro"
    public_ec2_instance_name = "public-ec2"
    private_ec2_instance_name = "private-ec2"
    ec2_instance_owner = "data-platform-team"
    ec2_instance_environment = "dev"
}
